engines:
 eslint:
   enabled: true
 pep8:
   enabled: true
checks:
  complex-logic:
    enabled: false
  method-lines:
    enabled: false
  nested-control-flow:
    enabled: false
  similar-code:
    enabled: false
ratings:
 paths:
 - "**.js"
 - "**.py"
exclude_paths:
- webpack.config.js
- "**/resources/**"
- js/test/**
- test/data/**
- web/lib/**
- tools/template/*
- "**/generated/*"
